# Generated by Django 4.2.5 on 2023-10-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="api",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("api_name", models.CharField(max_length=200)),
                ("api_url", models.CharField(max_length=200)),
                ("api_method", models.CharField(max_length=200)),
                ("api_count", models.IntegerField(default=0)),
                ("api_create_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="api_call",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("api_name", models.CharField(max_length=200)),
                ("api_url", models.CharField(max_length=200)),
                ("api_method", models.CharField(max_length=200)),
                ("api_call_times", models.IntegerField(default=0)),
                ("api_status", models.CharField(max_length=200)),
                ("api_ip", models.CharField(max_length=200)),
                ("api_user_id", models.CharField(max_length=200)),
                ("api_result", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="root",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=16)),
                ("password", models.CharField(max_length=32)),
            ],
        ),
    ]
