# Generated by Django 4.2.5 on 2023-10-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="api",
            name="api_detail",
            field=models.CharField(default="NONE", max_length=200),
        ),
    ]
