# Generated by Django 4.2.5 on 2023-10-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app1", "0002_api_api_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="api_call",
            name="api_call_times",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
