# Generated by Django 4.2.5 on 2023-10-07 06:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api_app1", "0003_alter_api_call_api_call_times"),
    ]

    operations = [
        migrations.RenameField(
            model_name="api_call",
            old_name="api_call_times",
            new_name="api_create_time",
        ),
        migrations.RenameField(
            model_name="api_call",
            old_name="api_result",
            new_name="api_question",
        ),
    ]
