# Generated by Django 4.2.5 on 2023-10-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app1", "0004_rename_api_call_times_api_call_api_create_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="api",
            name="api_params",
            field=models.CharField(default="NONE", max_length=200),
        ),
    ]
