# Generated by Django 4.2.5 on 2023-10-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app1", "0005_api_api_params"),
    ]

    operations = [
        migrations.AddField(
            model_name="api",
            name="api_class",
            field=models.CharField(default="ChatGPT", max_length=200),
        ),
    ]
