# Generated by Django 4.2.5 on 2023-10-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app1", "0006_api_api_class"),
    ]

    operations = [
        migrations.RenameField(
            model_name="api_call",
            old_name="api_status",
            new_name="api_protocol",
        ),
        migrations.AddField(
            model_name="api_call",
            name="api_UA",
            field=models.CharField(default="NONE", max_length=200),
        ),
    ]
