# Generated by Django 4.2.5 on 2023-10-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app1", "0007_rename_api_status_api_call_api_protocol_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="api",
            name="api_en_name",
            field=models.CharField(default="NONE", max_length=200),
        ),
    ]
